# Generated by Django 5.0 on 2023-12-19 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_daily_count_repeatcount_user_daily_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='global_total_count',
            new_name='global_total_repeat',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='per_user_daily_count',
            new_name='per_user_daily_repeat',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='per_user_total_count',
            new_name='per_user_total_repeat',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='per_user_weekly_count',
            new_name='per_user_weekly_repeat',
        ),
    ]
