# Generated by Django 5.0 on 2023-12-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_global_total_count_coupon_global_total_repeat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repeatcount',
            old_name='user_daily_count',
            new_name='user_daily_repeat',
        ),
        migrations.RenameField(
            model_name='repeatcount',
            old_name='user_monthly_count',
            new_name='user_total_repeat',
        ),
        migrations.RenameField(
            model_name='repeatcount',
            old_name='user_total_count',
            new_name='user_weekly_repeat',
        ),
        migrations.RemoveField(
            model_name='repeatcount',
            name='user_weekly_count',
        ),
    ]
