# Generated by Django 5.0 on 2023-12-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_user_daily_count_repeatcount_user_daily_repeat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repeatcount',
            name='user',
        ),
    ]
