# Generated by Django 5.0 on 2023-12-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_repeatcount_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repeatcount',
            name='global_total_repeat',
        ),
        migrations.RemoveField(
            model_name='repeatcount',
            name='user_daily_repeat',
        ),
        migrations.RemoveField(
            model_name='repeatcount',
            name='user_total_repeat',
        ),
        migrations.RemoveField(
            model_name='repeatcount',
            name='user_weekly_repeat',
        ),
    ]
